
server:
     port: 8090
spring:


  datasource:
    url: jdbc:mysql://localhost:3305/new?useSSL=false
    username: root
    password: admin
    
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        
        
        driverClassName: com.mysql.cj.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL8Dialect
